"""Utilities for building and loading the persistent Chroma vector store."""

from __future__ import annotations

import json
import math
import re
import time
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, Iterable, TypeVar

if TYPE_CHECKING:
    from langchain_core.documents import Document
    from langchain_core.embeddings import Embeddings


DEFAULT_CHUNKS_PATH = Path("data/processed/chunks.json")
DEFAULT_VECTOR_STORE_PATH = Path("data/vector_store")
DEFAULT_COLLECTION_NAME = "enterprise_ai_agent_docs"
DEFAULT_INDEX_BATCH_SIZE = 100
DEFAULT_BATCH_DELAY_SECONDS = 65.0
DEFAULT_MAX_RETRIES = 3

PrimitiveMetadataValue = str | int | float | bool
ProgressCallback = Callable[["IndexProgress"], None]
T = TypeVar("T")


class ChunkLoadError(ValueError):
    """Raised when chunks cannot be loaded from JSON."""


class VectorStoreConfigurationError(RuntimeError):
    """Raised when the vector store cannot be configured."""


@dataclass(frozen=True)
class ChunkRecord:
    """A normalized chunk loaded from ``chunks.json``."""

    chunk_id: str
    text: str
    metadata: dict[str, Any]


@dataclass(frozen=True)
class VectorStoreBuildResult:
    """Summary of a vector store indexing run."""

    persist_directory: Path
    collection_name: str
    document_count: int


@dataclass(frozen=True)
class IndexProgress:
    """Progress information emitted after each indexed batch."""

    indexed_count: int
    total_count: int
    batch_number: int
    batch_count: int
    next_delay_seconds: float


def load_chunk_records(chunks_file: str | Path = DEFAULT_CHUNKS_PATH) -> list[ChunkRecord]:
    """Load chunk records from the JSON generated by document processing."""
    chunks_path = Path(chunks_file)

    if not chunks_path.exists():
        raise FileNotFoundError(f"Chunks file not found: {chunks_path}")

    try:
        payload = json.loads(chunks_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ChunkLoadError(f"Invalid chunks JSON in {chunks_path}: {exc}") from exc

    raw_chunks = payload.get("chunks")
    if not isinstance(raw_chunks, list):
        raise ChunkLoadError("Chunks JSON must contain a top-level 'chunks' list.")

    records = [
        _chunk_record_from_payload(raw_chunk, index)
        for index, raw_chunk in enumerate(raw_chunks)
    ]
    records = [record for record in records if record.text.strip()]

    if not records:
        raise ChunkLoadError(f"No non-empty chunks found in {chunks_path}.")

    return records


def records_to_documents(records: Iterable[ChunkRecord]) -> list["Document"]:
    """Convert normalized chunks into LangChain ``Document`` objects."""
    document_cls = _document_class()
    documents: list[Document] = []

    for record in records:
        documents.append(
            document_cls(
                page_content=record.text,
                metadata=_document_metadata(record),
                id=record.chunk_id,
            )
        )

    return documents


def get_vector_store(
    embeddings: "Embeddings",
    persist_directory: str | Path = DEFAULT_VECTOR_STORE_PATH,
    collection_name: str = DEFAULT_COLLECTION_NAME,
) -> Any:
    """Open a persistent Chroma vector store for indexing or retrieval."""
    chroma_cls = _chroma_class()
    persist_path = Path(persist_directory)
    persist_path.mkdir(parents=True, exist_ok=True)

    return chroma_cls(
        collection_name=collection_name,
        embedding_function=embeddings,
        persist_directory=str(persist_path),
    )


def build_vector_store_from_chunks(
    chunks_file: str | Path,
    embeddings: "Embeddings",
    persist_directory: str | Path = DEFAULT_VECTOR_STORE_PATH,
    collection_name: str = DEFAULT_COLLECTION_NAME,
    reset_collection: bool = True,
    batch_size: int = DEFAULT_INDEX_BATCH_SIZE,
    batch_delay_seconds: float = DEFAULT_BATCH_DELAY_SECONDS,
    max_retries: int = DEFAULT_MAX_RETRIES,
    progress_callback: ProgressCallback | None = None,
) -> VectorStoreBuildResult:
    """Read chunks, embed them, and persist them into Chroma."""
    records = load_chunk_records(chunks_file)
    documents = records_to_documents(records)
    return index_documents(
        documents=documents,
        embeddings=embeddings,
        persist_directory=persist_directory,
        collection_name=collection_name,
        reset_collection=reset_collection,
        batch_size=batch_size,
        batch_delay_seconds=batch_delay_seconds,
        max_retries=max_retries,
        progress_callback=progress_callback,
    )


def index_documents(
    documents: list["Document"],
    embeddings: "Embeddings",
    persist_directory: str | Path = DEFAULT_VECTOR_STORE_PATH,
    collection_name: str = DEFAULT_COLLECTION_NAME,
    reset_collection: bool = True,
    batch_size: int = DEFAULT_INDEX_BATCH_SIZE,
    batch_delay_seconds: float = DEFAULT_BATCH_DELAY_SECONDS,
    max_retries: int = DEFAULT_MAX_RETRIES,
    progress_callback: ProgressCallback | None = None,
) -> VectorStoreBuildResult:
    """Embed and store LangChain documents in a persistent Chroma collection."""
    if not documents:
        raise ValueError("At least one document is required to build the vector store.")
    if batch_size <= 0:
        raise ValueError("batch_size must be greater than 0.")
    if batch_delay_seconds < 0:
        raise ValueError("batch_delay_seconds must be greater than or equal to 0.")
    if max_retries < 0:
        raise ValueError("max_retries must be greater than or equal to 0.")

    persist_path = Path(persist_directory)
    vector_store = get_vector_store(
        embeddings=embeddings,
        persist_directory=persist_path,
        collection_name=collection_name,
    )

    if reset_collection:
        _delete_collection(vector_store)
        vector_store = get_vector_store(
            embeddings=embeddings,
            persist_directory=persist_path,
            collection_name=collection_name,
        )

    indexed_count = 0
    batch_count = math.ceil(len(documents) / batch_size)

    for batch_number, document_batch in enumerate(
        _batched(documents, batch_size), start=1
    ):
        ids = [str(document.metadata["chunk_id"]) for document in document_batch]
        _add_documents_with_retries(
            vector_store=vector_store,
            documents=document_batch,
            ids=ids,
            max_retries=max_retries,
        )
        indexed_count += len(document_batch)

        next_delay = (
            batch_delay_seconds if batch_number < batch_count else 0.0
        )
        if progress_callback:
            progress_callback(
                IndexProgress(
                    indexed_count=indexed_count,
                    total_count=len(documents),
                    batch_number=batch_number,
                    batch_count=batch_count,
                    next_delay_seconds=next_delay,
                )
            )

        if next_delay > 0:
            time.sleep(next_delay)

    _persist_if_supported(vector_store)

    return VectorStoreBuildResult(
        persist_directory=persist_path,
        collection_name=collection_name,
        document_count=len(documents),
    )


def _chunk_record_from_payload(payload: Any, index: int) -> ChunkRecord:
    if not isinstance(payload, dict):
        raise ChunkLoadError(f"Chunk at index {index} must be an object.")

    text = payload.get("text")
    if not isinstance(text, str):
        raise ChunkLoadError(f"Chunk at index {index} must contain text.")

    metadata = payload.get("metadata", {})
    if not isinstance(metadata, dict):
        raise ChunkLoadError(f"Chunk metadata at index {index} must be an object.")

    chunk_id = str(payload.get("id") or f"chunk-{index:06d}")
    return ChunkRecord(chunk_id=chunk_id, text=text, metadata=metadata)


def _document_metadata(record: ChunkRecord) -> dict[str, PrimitiveMetadataValue]:
    metadata = record.metadata
    source = str(metadata.get("source") or metadata.get("file") or "")
    file_name = str(metadata.get("filename") or Path(source).name or "unknown")
    page = _coerce_page(_first_present(metadata, "page", "page_number"))

    document_metadata: dict[str, Any] = {
        "file": file_name,
        "page": page,
        "chunk_id": record.chunk_id,
        "source": source or file_name,
        "chunk_index": metadata.get("chunk_index"),
        "start_char": metadata.get("start_char"),
        "end_char": metadata.get("end_char"),
        "page_count": metadata.get("page_count"),
    }
    return _sanitize_metadata(document_metadata)


def _sanitize_metadata(metadata: dict[str, Any]) -> dict[str, PrimitiveMetadataValue]:
    sanitized: dict[str, PrimitiveMetadataValue] = {}

    for key, value in metadata.items():
        if value is None:
            continue

        if isinstance(value, (str, int, float, bool)):
            sanitized[key] = value
            continue

        sanitized[key] = str(value)

    return sanitized


def _coerce_page(value: Any) -> int:
    if value is None:
        return 0

    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def _first_present(metadata: dict[str, Any], *keys: str) -> Any:
    for key in keys:
        if key in metadata:
            return metadata[key]

    return None


def _document_class() -> type["Document"]:
    try:
        from langchain_core.documents import Document
    except ModuleNotFoundError as exc:
        raise VectorStoreConfigurationError(
            "Missing dependency: langchain-core. "
            "Install project dependencies before building the vector store."
        ) from exc

    return Document


def _chroma_class() -> Any:
    try:
        from langchain_chroma import Chroma

        return Chroma
    except ModuleNotFoundError:
        pass

    try:
        from langchain_community.vectorstores import Chroma

        return Chroma
    except ModuleNotFoundError as exc:
        raise VectorStoreConfigurationError(
            "Missing dependency: langchain-chroma. "
            "Install it with project dependencies before building the vector store."
        ) from exc


def _delete_collection(vector_store: Any) -> None:
    try:
        vector_store.delete_collection()
    except ValueError:
        return


def _persist_if_supported(vector_store: Any) -> None:
    persist = getattr(vector_store, "persist", None)
    if callable(persist):
        persist()


def _batched(items: list[T], batch_size: int) -> Iterable[list[T]]:
    for start in range(0, len(items), batch_size):
        yield items[start : start + batch_size]


def _add_documents_with_retries(
    vector_store: Any,
    documents: list["Document"],
    ids: list[str],
    max_retries: int,
) -> None:
    for attempt in range(max_retries + 1):
        try:
            vector_store.add_documents(documents, ids=ids)
            return
        except Exception as exc:
            if attempt >= max_retries or not _is_retryable_embedding_error(exc):
                raise

            time.sleep(_retry_delay_seconds(exc))


def _is_retryable_embedding_error(exc: Exception) -> bool:
    message = str(exc).lower()
    return (
        "resource_exhausted" in message
        or "429" in message
        or "quota" in message
        or "rate" in message
    )


def _retry_delay_seconds(exc: Exception) -> float:
    message = str(exc)
    patterns = (
        r"retryDelay['\"]?\s*:\s*['\"](?P<seconds>\d+(?:\.\d+)?)s",
        r"retry in (?P<seconds>\d+(?:\.\d+)?)s",
    )

    for pattern in patterns:
        match = re.search(pattern, message, flags=re.IGNORECASE)
        if match:
            return float(match.group("seconds")) + 2.0

    return 30.0
